import { Person, Account } from '@/types';
export const PEOPLE: Person[] = [
  { id: 1,  name: 'สกาย',      emoji: '👑', tag: 'ประธาน',            photo: '/people/1.png'},
  { id: 2,  name: 'ข้าวจ้าว',  emoji: '💰', tag: 'อำนวยการคลัง',      photo: '/people/2.jpeg' },
  { id: 3,  name: 'ส้มส้ม',    emoji: '📝', tag: 'เลขานุการ',          photo: '/people/3.JPG' },
  { id: 4,  name: 'แน้ม',      emoji: '🎪', tag: 'กิจกรรม',            photo: '/people/4.jpeg' },
  { id: 5,  name: 'ทอมปาล์ม', emoji: '⚖️', tag: 'พิทักษ์สิทธิ์',     photo: '/people/5.JPG' },
  { id: 6,  name: 'คะนิ้ง',   emoji: '🤝', tag: 'ทรัพยากรบุคคล',     photo: '/people/6.JPG' },
  { id: 7,  name: 'ชมพู่',     emoji: '📚', tag: 'วิชาการ',            photo: '/people/7.JPG' },
  { id: 8,  name: 'วีไวท์',   emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/8.png' },
  { id: 9,  name: 'โอเว่น',   emoji: '📦', tag: 'พัสดุ',              photo: '/people/9.JPG'  },
  { id: 10, name: 'สายฟ้า',   emoji: '📦', tag: 'พัสดุ',              photo: '/people/10.JPG'  },
  { id: 11, name: 'ภู',        emoji: '📦', tag: 'พัสดุ',              photo: '/people/11.JPG'  },
  { id: 12, name: 'แยมส้ม',   emoji: '📚', tag: 'วิชาการ',            photo: '/people/12.JPG'  },
  { id: 13, name: 'แพท',      emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/13.png'  },
  { id: 14, name: 'ฟามัส',    emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/14.JPG'  },
  { id: 15, name: 'ทิวลิป',   emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/15.JPG'  },
  { id: 16, name: 'คิตตี้',   emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/16.JPG'  },
  { id: 17, name: 'มังกร',    emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/17.jpeg'  },
  { id: 18, name: 'ตังตัง',   emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/18.JPG'  },
  { id: 19, name: 'มาเบล',    emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/19.jpeg'  },
  { id: 20, name: 'เก็ท',     emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/20.JPG'  },
  { id: 21, name: 'มอส',      emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/21.jpg'  },
  { id: 22, name: 'ซี',       emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/22.JPG'  },
  { id: 23, name: 'แพรวา',    emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: '/people/23.JPG'  },
  { id: 24, name: 'เชียร์',   emoji: '📊', tag: 'แผนงบ',              photo: '/people/24.JPG'  },
  { id: 25, name: 'อาย',      emoji: '📝', tag: 'เลขานุการ',          photo: '/people/25.JPG'  },
  { id: 26, name: 'ครีม',     emoji: '📝', tag: 'เลขานุการ',          photo: '/people/26.JPG'  },
  { id: 27, name: 'ดรีม',     emoji: '📝', tag: 'เลขานุการ',          photo: '/people/27.jpeg'  },
  { id: 28, name: 'ไอซ์',     emoji: '📝', tag: 'เลขานุการ',          photo: '/people/28.JPG'  },
  { id: 29, name: 'ปาล์มโซฮี',emoji: '⚖️', tag: 'พิทักษ์สิทธิ์',     photo: '/people/29.JPG'  },
  { id: 30, name: 'ปลายฝน',   emoji: '⚖️', tag: 'พิทักษ์สิทธิ์',     photo: '/people/30.JPG'  },
  { id: 31, name: 'อิีงค์',   emoji: '🔗', tag: 'ประสานงาน',          photo: '/people/31.JPG'  },
  { id: 32, name: 'จูเน่',    emoji: '🔗', tag: 'ประสานงาน',          photo: '/people/32.JPG'  },
  { id: 33, name: 'จูน',      emoji: '🔗', tag: 'ประสานงาน',          photo: '/people/33.JPG'  },
  { id: 34, name: 'ณพ',       emoji: '🔗', tag: 'ประสานงาน',          photo: '/people/34.jpeg'  },
  { id: 35, name: 'เมย์',     emoji: '🔗', tag: 'ประสานงาน',          photo: '/people/35.jpeg'  },
  { id: 36, name: 'พิม',      emoji: '🔗', tag: 'ประสานงาน',          photo: '/people/36.JPG'  },
  { id: 37, name: 'ฮ่องเต้',  emoji: '🎪', tag: 'กิจกรรม',            photo: '/people/37.JPG'  },
  { id: 38, name: 'ปิงปอง',   emoji: '🎪', tag: 'กิจกรรม',            photo: '/people/38.jpg'  },
  { id: 39, name: 'โฟร์วีล',  emoji: '🎪', tag: 'กิจกรรม',            photo: '/people/39.JPG'  },
  { id: 40, name: 'ชมพู่เล็ก',emoji: '🎪', tag: 'กิจกรรม',            photo: '/people/40.JPG'  },
  { id: 41, name: 'เกรซ',     emoji: '🎪', tag: 'กิจกรรม',            photo: '/people/41.JPG'  },
  { id: 42, name: 'อั้ม',     emoji: '🤝', tag: 'ทรัพยากรบุคคล',     photo: '/people/42.JPG'  },
  { id: 43, name: 'เค้ก',     emoji: '🤝', tag: 'ทรัพยากรบุคคล',     photo: '/people/43.JPG'  },
  { id: 44, name: 'เมษา',     emoji: '🤝', tag: 'ทรัพยากรบุคคล',     photo: '/people/44.JPG'  },
];
// ⚠️ production: ย้าย password ไปเก็บ hash ใน DB หรือ NextAuth
export const ACCOUNTS: Account[] = [
  { username: 'sky',        password: 'mK7pX2', personId: 1  },
  { username: 'khaojao',    password: 'Tz4wR9', personId: 2  },
  { username: 'somsom',     password: 'Yc8vN3', personId: 3  },
  { username: 'nam',        password: 'Qh5sD6', personId: 4  },
  { username: 'tom-palm',   password: 'Xr2kG7', personId: 5  },
  { username: 'kaning',     password: 'Bn9tL4', personId: 6  },
  { username: 'chompoo',    password: 'Wf3yM8', personId: 7  },
  { username: 'weewhite',   password: 'Jd6uH2', personId: 8  },
  { username: 'owen',       password: 'Pk4rB9', personId: 9  },
  { username: 'saifah',     password: 'Lv7wC5', personId: 10 },
  { username: 'phu',        password: 'Rg2qF8', personId: 11 },
  { username: 'yamsom',     password: 'Hx5nJ3', personId: 12 },
  { username: 'pat',        password: 'Cm9bW6', personId: 13 },
  { username: 'famus',      password: 'Zt4sQ7', personId: 14 },
  { username: 'tulip',      password: 'Av8mK2', personId: 15 },
  { username: 'kitty',      password: 'Nf3xD9', personId: 16 },
  { username: 'mangkorn',   password: 'Sq6tH4', personId: 17 },
  { username: 'tangtang',   password: 'Ej7vR2', personId: 18 },
  { username: 'mabel',      password: 'Yw5kM8', personId: 19 },
  { username: 'get',        password: 'Dp3qN6', personId: 20 },
  { username: 'mos',        password: 'Uc9wL4', personId: 21 },
  { username: 'sea',        password: 'Mk2rB7', personId: 22 },
  { username: 'praewa',     password: 'Tn8yG5', personId: 23 },
  { username: 'cheer',      password: 'Fx4dW3', personId: 24 },
  { username: 'eye',        password: 'Bw6mK9', personId: 25 },
  { username: 'cream',      password: 'Zs2vH7', personId: 26 },
  { username: 'dream',      password: 'Qp5xE4', personId: 27 },
  { username: 'ice',        password: 'Gy3nF8', personId: 28 },
  { username: 'palm',       password: 'Rc7kJ2', personId: 29 },
  { username: 'pyne',       password: 'Vh9tQ6', personId: 30 },
  { username: 'ink',        password: 'Ew4sB3', personId: 31 },
  { username: 'june1',      password: 'Lm8rC7', personId: 32 },
  { username: 'june2',      password: 'Aq5nW2', personId: 33 },
  { username: 'nop',        password: 'Tj6vM9', personId: 34 },
  { username: 'may',        password: 'Xs3wG4', personId: 35 },
  { username: 'pim',        password: 'Dn7qR8', personId: 36 },
  { username: 'hongte',     password: 'Bf2yL5', personId: 37 },
  { username: 'pingpong',   password: 'Wc9tN3', personId: 38 },
  { username: 'fourwheel',  password: 'Kp4sH6', personId: 39 },
  { username: 'chompoo-lek',password: 'Yr8mD2', personId: 40 },
  { username: 'grace',      password: 'Gu5bT7', personId: 41 },
  { username: 'aum',        password: 'Mx3kQ9', personId: 42 },
  { username: 'cake',       password: 'Nv6pE4', personId: 43 },
  { username: 'mesa',       password: 'Zh2wB8', personId: 44 },
];