import { Person, Account } from '@/types';
export const PEOPLE: Person[] = [
  { id: 1,  name: 'สกาย',      emoji: '👑', tag: 'ประธาน',            photo: 'https://ibb.co/M5BkD665'},
  { id: 2,  name: 'ข้าวจ้าว',  emoji: '💰', tag: 'อำนวยการคลัง',      photo: 'https://ibb.co/wZKskbHq' },
  { id: 3,  name: 'ส้มส้ม',    emoji: '📝', tag: 'เลขานุการ',          photo: undefined },
  { id: 4,  name: 'แน้ม',      emoji: '🎪', tag: 'กิจกรรม',            photo: undefined },
  { id: 5,  name: 'ทอมปาล์ม', emoji: '⚖️', tag: 'พิทักษ์สิทธิ์',     photo: undefined },
  { id: 6,  name: 'คะนิ้ง',   emoji: '🤝', tag: 'ทรัพยากรบุคคล',     photo: undefined },
  { id: 7,  name: 'ชมพู่',     emoji: '📚', tag: 'วิชาการ',            photo: undefined },
  { id: 8,  name: 'วีไวท์',   emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 9,  name: 'โอเว่น',   emoji: '📦', tag: 'พัสดุ',              photo: undefined },
  { id: 10, name: 'สายฟ้า',   emoji: '📦', tag: 'พัสดุ',              photo: undefined },
  { id: 11, name: 'ภู',        emoji: '📦', tag: 'พัสดุ',              photo: undefined },
  { id: 12, name: 'แยมส้ม',   emoji: '📚', tag: 'วิชาการ',            photo: undefined },
  { id: 13, name: 'แพท',      emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 14, name: 'ฟามัส',    emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 15, name: 'ทิวลิป',   emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 16, name: 'คิตตี้',   emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 17, name: 'มังกร',    emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 18, name: 'ตังตัง',   emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 19, name: 'มาเบล',    emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 20, name: 'เก็ท',     emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 21, name: 'มอส',      emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 22, name: 'ซี',       emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 23, name: 'แพรวา',    emoji: '📢', tag: 'ประชาสัมพันธ์',      photo: undefined },
  { id: 24, name: 'เชียร์',   emoji: '📊', tag: 'แผนงบ',              photo: undefined },
  { id: 25, name: 'อาย',      emoji: '📝', tag: 'เลขานุการ',          photo: undefined },
  { id: 26, name: 'ครีม',     emoji: '📝', tag: 'เลขานุการ',          photo: undefined },
  { id: 27, name: 'ดรีม',     emoji: '📝', tag: 'เลขานุการ',          photo: undefined },
  { id: 28, name: 'ไอซ์',     emoji: '📝', tag: 'เลขานุการ',          photo: undefined },
  { id: 29, name: 'ปาล์มโซฮี',emoji: '⚖️', tag: 'พิทักษ์สิทธิ์',     photo: undefined },
  { id: 30, name: 'ปลายฝน',   emoji: '⚖️', tag: 'พิทักษ์สิทธิ์',     photo: undefined },
  { id: 31, name: 'อิีงค์',   emoji: '🔗', tag: 'ประสานงาน',          photo: undefined },
  { id: 32, name: 'จูเน่',    emoji: '🔗', tag: 'ประสานงาน',          photo: undefined },
  { id: 33, name: 'จูน',      emoji: '🔗', tag: 'ประสานงาน',          photo: undefined },
  { id: 34, name: 'ณพ',       emoji: '🔗', tag: 'ประสานงาน',          photo: undefined },
  { id: 35, name: 'เมย์',     emoji: '🔗', tag: 'ประสานงาน',          photo: undefined },
  { id: 36, name: 'พิม',      emoji: '🔗', tag: 'ประสานงาน',          photo: undefined },
  { id: 37, name: 'ฮ่องเต้',  emoji: '🎪', tag: 'กิจกรรม',            photo: undefined },
  { id: 38, name: 'ปิงปอง',   emoji: '🎪', tag: 'กิจกรรม',            photo: undefined },
  { id: 39, name: 'โฟร์วีล',  emoji: '🎪', tag: 'กิจกรรม',            photo: undefined },
  { id: 40, name: 'ชมพู่เล็ก',emoji: '🎪', tag: 'กิจกรรม',            photo: undefined },
  { id: 41, name: 'เกรซ',     emoji: '🎪', tag: 'กิจกรรม',            photo: undefined },
  { id: 42, name: 'อั้ม',     emoji: '🤝', tag: 'ทรัพยากรบุคคล',     photo: undefined },
  { id: 43, name: 'เค้ก',     emoji: '🤝', tag: 'ทรัพยากรบุคคล',     photo: undefined },
  { id: 44, name: 'เมษา',     emoji: '🤝', tag: 'ทรัพยากรบุคคล',     photo: undefined },
];

// ⚠️ production: ย้าย password ไปเก็บ hash ใน DB หรือ NextAuth
export const ACCOUNTS: Account[] = [
  { username: 'sky',       password: 'pass01', personId: 1  },
  { username: 'khaojao',   password: 'pass02', personId: 2  },
  { username: 'somsom',    password: 'pass03', personId: 3  },
  { username: 'naem',      password: 'pass04', personId: 4  },
  { username: 'tompalm',   password: 'pass05', personId: 5  },
  { username: 'khaning',   password: 'pass06', personId: 6  },
  { username: 'chompoo',   password: 'pass07', personId: 7  },
  { username: 'veewhite',  password: 'pass08', personId: 8  },
  { username: 'owen',      password: 'pass09', personId: 9  },
  { username: 'saifah',    password: 'pass10', personId: 10 },
  { username: 'phu',       password: 'pass11', personId: 11 },
  { username: 'yamsom',    password: 'pass12', personId: 12 },
  { username: 'pat',       password: 'pass13', personId: 13 },
  { username: 'famous',    password: 'pass14', personId: 14 },
  { username: 'tulip',     password: 'pass15', personId: 15 },
  { username: 'kitty',     password: 'pass16', personId: 16 },
  { username: 'mangkon',   password: 'pass17', personId: 17 },
  { username: 'tangtang',  password: 'pass18', personId: 18 },
  { username: 'mabel',     password: 'pass19', personId: 19 },
  { username: 'get',       password: 'pass20', personId: 20 },
  { username: 'moss',      password: 'pass21', personId: 21 },
  { username: 'zee',       password: 'pass22', personId: 22 },
  { username: 'praewa',    password: 'pass23', personId: 23 },
  { username: 'cheer',     password: 'pass24', personId: 24 },
  { username: 'eye',       password: 'pass25', personId: 25 },
  { username: 'cream',     password: 'pass26', personId: 26 },
  { username: 'dream',     password: 'pass27', personId: 27 },
  { username: 'ice',       password: 'pass28', personId: 28 },
  { username: 'palmsohi',  password: 'pass29', personId: 29 },
  { username: 'plaifon',   password: 'pass30', personId: 30 },
  { username: 'ink',       password: 'pass31', personId: 31 },
  { username: 'june1',     password: 'pass32', personId: 32 },
  { username: 'june2',     password: 'pass33', personId: 33 },
  { username: 'nop',       password: 'pass34', personId: 34 },
  { username: 'may',       password: 'pass35', personId: 35 },
  { username: 'pim',       password: 'pass36', personId: 36 },
  { username: 'hongte',    password: 'pass37', personId: 37 },
  { username: 'pingpong',  password: 'pass38', personId: 38 },
  { username: 'fourwheel', password: 'pass39', personId: 39 },
  { username: 'chompoolek',password: 'pass40', personId: 40 },
  { username: 'grace',     password: 'pass41', personId: 41 },
  { username: 'um',        password: 'pass42', personId: 42 },
  { username: 'cake',      password: 'pass43', personId: 43 },
  { username: 'mesa',      password: 'pass44', personId: 44 },
];


